import {DEFAULTS,settings,next,reset,restore,save,serialize,raster,toggle,undo,hit,svg} from './core.mjs';
const $=id=>document.getElementById(id), key=location.pathname.toLowerCase().startsWith('/tools/arosaegida')?'magic-qr-session-v1-arosaegida':'magic-qr-session-v1';let state={config:{...DEFAULTS},counter:0,frozen:false,current:null};let storageIssue=false;try{const raw=localStorage.getItem(key);if(raw){state=restore(raw);}}catch{storageIssue=true;}
if(!state.config.target)state.config=settings(DEFAULTS);reset(state);
function persist(){let ok=false;try{ok=save(localStorage,key,state);}catch{}if(!ok){storageIssue=true;notice('이 기기에 저장할 수 없습니다. 설정에서 백업하세요.');}}
function notice(message){$('notice').textContent=message;}
function render(){const q=state.current;$('empty').hidden=!!q;$('empty').textContent=state.config.target?'생성을 눌러 주세요.':'설정을 완료해 주세요.';$('qr').hidden=!q;$('generate').disabled=state.frozen||!state.config.target;$('freeze').disabled=!q;$('freeze').textContent=state.frozen?'고정됨':'고정';$('freeze').setAttribute('aria-pressed',String(state.frozen));$('editbar').hidden=!state.frozen;$('undo').disabled=!q?.history.length;if(q){const r=raster(q,16);$('qr').width=r.width;$('qr').height=r.height;$('qr').getContext('2d').putImageData(new ImageData(r.data,r.width,r.height),0,0);}}
function open(){ $('target').value=state.config.target;$('ordinal').value=state.config.ordinal;$('decoys').value=state.config.decoys.join('\n');$('session').textContent=`현재 생성 횟수: ${state.counter}${state.frozen?' · 고정 중':''}`;$('error').textContent=storageIssue?'기기 저장을 사용할 수 없거나 저장 내용이 올바르지 않습니다. 백업을 권장합니다.':'';if(!$('settings').open)$('settings').showModal(); }
$('setup').onclick=open;$('close').onclick=()=>$('settings').close();document.addEventListener('keydown',e=>{if(e.shiftKey&&e.key==='Escape'){e.preventDefault();open();}});
$('form').onsubmit=e=>{e.preventDefault();try{const config=settings({target:$('target').value,ordinal:$('ordinal').value,decoys:$('decoys').value});state.config=config;reset(state);persist();render();$('settings').close();}catch(err){$('error').textContent=err.message;}};
$('generate').onclick=()=>{try{if(next(state)){persist();notice('');render();}}catch(err){notice('생성할 수 없습니다. 설정을 확인하세요.');console.error(err);}};
$('freeze').onclick=()=>{state.frozen=true;persist();render();};$('undo').onclick=()=>{if(state.current){undo(state.current);persist();render();}};$('clean').onclick=()=>{if(state.current){state.current.edits.clear();state.current.history=[];persist();render();}};$('rehearsal').onclick=()=>{reset(state);persist();render();open();};
const pointers=new Map();let gesture=null,blocked=false;
document.addEventListener('pointerdown',e=>{if($('settings').open)return;pointers.set(e.pointerId,{x:e.clientX,y:e.clientY,startX:e.clientX,startY:e.clientY,target:e.target});if(pointers.size===1)blocked=false;if(pointers.size===2){blocked=true;gesture={ids:[...pointers.keys()],start:[...pointers.values()].map(p=>({x:p.x,y:p.y}))};}});
document.addEventListener('pointermove',e=>{const p=pointers.get(e.pointerId);if(p){p.x=e.clientX;p.y=e.clientY;if(Math.hypot(p.x-p.startX,p.y-p.startY)>8)p.drag=true;}if(gesture&&!$('settings').open){const pair=gesture.ids.map(id=>pointers.get(id));if(pair.every(Boolean)&&pair.every((p,i)=>p.y-gesture.start[i].y>65&&Math.abs(p.x-gesture.start[i].x)<90)){open();gesture=null;}}});
document.addEventListener('pointerup',e=>{const p=pointers.get(e.pointerId);if(p&&p.target===$('qr')&&!p.drag&&Math.hypot(e.clientX-p.startX,e.clientY-p.startY)<=8&&!blocked&&state.frozen&&!$('settings').open){const cell=hit($('qr').getBoundingClientRect(),state.current.size,e.clientX,e.clientY);if(cell){const result=toggle(state.current,cell.x,cell.y);if(result.ok){persist();notice('');render();}else notice(result.reason==='protected'?'이 부분은 고정되어 있습니다.':'이 변경은 적용할 수 없습니다.');}}pointers.delete(e.pointerId);if(!pointers.size){gesture=null;blocked=false;}});document.addEventListener('pointercancel',e=>{pointers.delete(e.pointerId);blocked=true;gesture=null;});window.addEventListener('blur',()=>{pointers.clear();gesture=null;blocked=false;});
function download(blob,name){const link=document.createElement('a'),href=URL.createObjectURL(blob);link.href=href;link.download=name;link.click();setTimeout(()=>URL.revokeObjectURL(href),1000);}
$('png').onclick=()=>{if(state.current)$('qr').toBlob(blob=>{if(blob)download(blob,'QR.png');});};$('svg').onclick=()=>{const q=state.current;if(!q)return;download(new Blob([svg(q)],{type:'image/svg+xml'}),'QR.svg');};$('backup').onclick=()=>download(new Blob([serialize(state)],{type:'application/json'}),'QR-backup.json');$('import').onchange=async e=>{try{const file=e.target.files[0];if(!file)return;if(file.size>100000)throw Error('백업 파일이 너무 큽니다.');state=restore(await file.text());persist();render();open();}catch{$('error').textContent='올바른 QR 백업 파일이 아닙니다.';}finally{e.target.value='';}};
persist();render();if(storageIssue)notice('기기 저장을 사용할 수 없거나 저장 내용이 올바르지 않습니다. 설정에서 백업을 확인하세요.');if('serviceWorker'in navigator)navigator.serviceWorker.register('./sw.js',{scope:'./'}).catch(()=>{});
