import {DEFAULTS,settings,next,reset,restore,save,serialize,raster,toggle,undo,hit,svg} from './core.mjs';
const $=id=>document.getElementById(id), key=location.pathname.toLowerCase().startsWith('/tools/arosaegida')?'magic-qr-session-v1-arosaegida':'magic-qr-session-v1';let state={config:{...DEFAULTS},counter:0,frozen:false,current:null};let storageIssue=false;try{const raw=localStorage.getItem(key);if(raw){state=restore(raw);}}catch{storageIssue=true;}
if(!state.config.target)state.config=settings(DEFAULTS);reset(state);
function persist(){let ok=false;try{ok=save(localStorage,key,state);}catch{}if(!ok){storageIssue=true;notice('이 기기에 저장할 수 없습니다. 설정에서 백업하세요.');}}
function notice(message){$('notice').textContent=message;}
function render(){const q=state.current;$('empty').hidden=!!q;$('empty').textContent=state.config.target?'생성을 눌러 주세요.':'설정을 완료해 주세요.';$('qr').hidden=!q;$('generate').disabled=state.frozen||!state.config.target;$('freeze').disabled=!q;$('freeze').textContent=state.frozen?'고정됨':'고정';$('freeze').setAttribute('aria-pressed',String(state.frozen));$('editbar').hidden=!state.frozen;$('undo').disabled=!q?.history.length;if(q){const r=raster(q,16);$('qr').width=r.width;$('qr').height=r.height;$('qr').getContext('2d').putImageData(new ImageData(r.data,r.width,r.height),0,0);}}
function open(){ renderInstall();$('target').value=state.config.target;$('ordinal').value=state.config.ordinal;$('decoys').value=state.config.decoys.join('\n');$('session').textContent=`현재 생성 횟수: ${state.counter}${state.frozen?' · 고정 중':''}`;$('error').textContent=storageIssue?'기기 저장을 사용할 수 없거나 저장 내용이 올바르지 않습니다. 백업을 권장합니다.':'';if(!$('settings').open)$('settings').showModal(); }
$('setup').onclick=open;$('close').onclick=()=>$('settings').close();document.addEventListener('keydown',e=>{if(e.shiftKey&&e.key==='Escape'){e.preventDefault();open();}});
$('form').onsubmit=e=>{e.preventDefault();try{const config=settings({target:$('target').value,ordinal:$('ordinal').value,decoys:$('decoys').value});state.config=config;reset(state);persist();render();$('settings').close();}catch(err){$('error').textContent=err.message;}};
$('generate').onclick=()=>{try{if(next(state)){persist();notice('');render();}}catch(err){notice('생성할 수 없습니다. 설정을 확인하세요.');console.error(err);}};
$('freeze').onclick=()=>{state.frozen=true;persist();render();};$('undo').onclick=()=>{if(state.current){undo(state.current);persist();render();}};$('clean').onclick=()=>{if(state.current){state.current.edits.clear();state.current.history=[];persist();render();}};$('rehearsal').onclick=()=>{reset(state);persist();render();open();};
const pointers=new Map();let gesture=null,blocked=false;
document.addEventListener('pointerdown',e=>{if($('settings').open)return;pointers.set(e.pointerId,{x:e.clientX,y:e.clientY,startX:e.clientX,startY:e.clientY,target:e.target});if(pointers.size===1)blocked=false;if(pointers.size===2){blocked=true;gesture={ids:[...pointers.keys()],start:[...pointers.values()].map(p=>({x:p.x,y:p.y}))};}});
document.addEventListener('pointermove',e=>{const p=pointers.get(e.pointerId);if(p){p.x=e.clientX;p.y=e.clientY;if(Math.hypot(p.x-p.startX,p.y-p.startY)>8)p.drag=true;}if(gesture&&!$('settings').open){const pair=gesture.ids.map(id=>pointers.get(id));if(pair.every(Boolean)&&pair.every((p,i)=>p.y-gesture.start[i].y>65&&Math.abs(p.x-gesture.start[i].x)<90)){open();gesture=null;}}});
document.addEventListener('pointerup',e=>{const p=pointers.get(e.pointerId);if(p&&p.target===$('qr')&&!p.drag&&Math.hypot(e.clientX-p.startX,e.clientY-p.startY)<=8&&!blocked&&state.frozen&&!$('settings').open){const cell=hit($('qr').getBoundingClientRect(),state.current.size,e.clientX,e.clientY);if(cell){const result=toggle(state.current,cell.x,cell.y);if(result.ok){persist();notice('');render();}else notice(result.reason==='protected'?'이 부분은 고정되어 있습니다.':'이 변경은 적용할 수 없습니다.');}}pointers.delete(e.pointerId);if(!pointers.size){gesture=null;blocked=false;}});document.addEventListener('pointercancel',e=>{pointers.delete(e.pointerId);blocked=true;gesture=null;});window.addEventListener('blur',()=>{pointers.clear();gesture=null;blocked=false;});
function download(blob,name){const link=document.createElement('a'),href=URL.createObjectURL(blob);link.href=href;link.download=name;link.click();setTimeout(()=>URL.revokeObjectURL(href),1000);}
$('png').onclick=()=>{if(state.current)$('qr').toBlob(blob=>{if(blob)download(blob,'QR.png');});};$('svg').onclick=()=>{const q=state.current;if(!q)return;download(new Blob([svg(q)],{type:'image/svg+xml'}),'QR.svg');};$('backup').onclick=()=>download(new Blob([serialize(state)],{type:'application/json'}),'QR-backup.json');$('import').onchange=async e=>{try{const file=e.target.files[0];if(!file)return;if(file.size>100000)throw Error('백업 파일이 너무 큽니다.');state=restore(await file.text());persist();render();open();}catch{$('error').textContent='올바른 QR 백업 파일이 아닙니다.';}finally{e.target.value='';}};
let deferredPrompt=null,installSignal='none';
function standaloneDisplay(){let mode=false;try{if(typeof window.matchMedia==='function')mode=window.matchMedia('(display-mode: standalone)').matches||window.matchMedia('(display-mode: window-controls-overlay)').matches;}catch{}return mode||navigator.standalone===true;}
function installManual(){const ua=String(navigator.userAgent||''),platform=String(navigator.platform||''),touch=Number(navigator.maxTouchPoints)||0,ios=/iPad|iPhone|iPod/.test(ua)||(platform==='MacIntel'&&touch>1),android=/Android/i.test(ua);if(!ua)return '설치 창이 없으면 브라우저 메뉴를 확인하세요. Android Chrome은 ‘앱 설치’ 또는 ‘홈 화면에 추가’, iPhone·iPad의 Safari는 공유 버튼의 ‘홈 화면에 추가’, 데스크톱 Chromium은 주소창이나 메뉴의 앱 설치입니다. 홈 화면 항목과 바로가기는 설치된 앱과 다를 수 있습니다. 이 페이지는 시스템 앱 목록을 확인하지 않습니다.';if(ios)return 'Safari에서 공유 버튼을 누른 뒤 ‘홈 화면에 추가’를 선택하세요. ‘웹 앱으로 열기’가 보이면 켜고 추가하세요. 홈 화면에서 아로새기다 아이콘을 찾으세요. App Store에서 받은 앱과는 다른 웹 앱이며, 앱 보관함 표시 방식은 OS 버전에 따라 다릅니다.';if(android)return 'Chrome 메뉴의 ‘앱 설치’는 설치 흐름이고, ‘홈 화면에 추가’는 바로가기일 수 있습니다. 이 페이지는 앱 서랍을 검사하지 못합니다. 인앱 브라우저라면 기본 브라우저로 여세요.';return '데스크톱 Chromium에서는 주소창의 설치 아이콘이나 메뉴의 앱 설치를 사용하세요. 설치되면 브라우저 앱 목록과 운영체제가 정한 앱 위치에 나올 수 있습니다. 이 페이지는 그 위치를 확인하지 않습니다. 설치를 지원하지 않는 브라우저는 바로가기만 만들 수 있으며, 바로가기는 설치된 앱이 아닙니다.';}
function promptReady(event){return !!event&&event.isTrusted!==false&&typeof event.prompt==='function'&&!!event.userChoice&&typeof event.userChoice.then==='function';}
function installStatus(){const parts=[];if(standaloneDisplay())parts.push('지금은 단독 창입니다. 홈 화면에서 연 바로가기일 수도 있고 설치된 앱일 수도 있습니다. 시스템 앱 목록을 읽어 구분하지는 않습니다.');else parts.push('지금은 브라우저 탭입니다. 이 페이지는 기기를 검사하지 않으므로 설치 여부를 여기서 확정할 수 없습니다.');if(installSignal==='appinstalled')parts.push('이번 페이지에서 브라우저가 설치 완료 신호를 보냈습니다. 앱 서랍, 시작 메뉴, 런치패드, 앱 보관함에 있는지는 확인하지 않습니다.');else if(installSignal==='accepted')parts.push('브라우저에는 설치에 동의했다고만 응답했습니다. 동의만으로 설치 완료가 아닙니다.');else if(installSignal==='error')parts.push('설치 창을 열지 못했습니다. 브라우저 메뉴에서 다시 시도하세요.');else if(installSignal==='dismissed')parts.push('설치 확인 창을 닫았습니다. 설치 완료가 아닙니다.');parts.push('앱 이름은 아로새기다이며, 이전 설치는 QR로 남아 있을 수 있습니다. 두 이름을 검색해 보세요. 목록에 없어도 그것만으로 오류는 아닙니다. 홈 화면, 브라우저 앱 목록, iPhone·iPad 앱 보관함을 각각 확인해 보세요. 이미 있는 설치는 제거하지 않습니다.');return parts.join(' ');}
function renderInstall(){const status=$('install-status'),button=$('install'),manual=$('install-manual');if(!status||!button||!manual)return;const ready=promptReady(deferredPrompt)&&!standaloneDisplay()&&installSignal!=='appinstalled';status.textContent=installStatus();manual.textContent=installManual();button.hidden=!ready;button.disabled=!ready;}
function watchDisplay(){try{if(typeof window.matchMedia!=='function')return;for(const query of ['(display-mode: standalone)','(display-mode: window-controls-overlay)']){const media=window.matchMedia(query);if(typeof media.addEventListener==='function')media.addEventListener('change',renderInstall);}}catch{}}
window.addEventListener('beforeinstallprompt',event=>{if(!promptReady(event)||standaloneDisplay()||installSignal==='appinstalled')return;if(typeof event.preventDefault==='function')event.preventDefault();deferredPrompt=event;renderInstall();});
window.addEventListener('appinstalled',()=>{deferredPrompt=null;installSignal='appinstalled';renderInstall();});
$('install').onclick=async()=>{const event=deferredPrompt;if(!promptReady(event))return;deferredPrompt=null;renderInstall();try{await event.prompt();const choice=await event.userChoice;if(installSignal!=='appinstalled')installSignal=choice&&choice.outcome==='accepted'?'accepted':'dismissed';}catch{if(installSignal!=='appinstalled')installSignal='error';}renderInstall();};
watchDisplay();
persist();render();renderInstall();if(storageIssue)notice('기기 저장을 사용할 수 없거나 저장 내용이 올바르지 않습니다. 설정에서 백업을 확인하세요.');if('serviceWorker'in navigator)navigator.serviceWorker.register('./sw.js',{scope:'./'}).catch(()=>{});
