export const DEFAULTS_REVISION=2;
// Percent of a full-cell circle's diameter. 100 is radius 0.5; above that the circle bleeds into neighboring modules.
export const DOT_PERCENT_MIN=100,DOT_PERCENT_MAX=130,DOT_PERCENT_STEP=5,DOT_PERCENT_DEFAULT=120;
export const DOT_RADIUS=DOT_PERCENT_DEFAULT/200;
export function assertDot(value){let n=NaN;if(typeof value==='number')n=value;else if(typeof value==='string'&&/^[0-9]+$/.test(value.trim()))n=Number(value.trim());if(!Number.isInteger(n)||n<DOT_PERCENT_MIN||n>DOT_PERCENT_MAX||(n-DOT_PERCENT_MIN)%DOT_PERCENT_STEP!==0)throw Error(`점 크기는 ${DOT_PERCENT_MIN}%에서 ${DOT_PERCENT_MAX}%까지 ${DOT_PERCENT_STEP}% 단위여야 합니다.`);return n;}
const LEGACY_DEFAULTS={target:'https://www.instagram.com/p/CARmsi2HRlV/',decoys:['https://lnmagic.co.kr/','https://www.youtube.com/','https://thirtymall.com/','https://www.penguinmagic.com/','https://cafe.naver.com/conjuring','https://www.naver.com/','https://music.youtube.com/']};
export const DEFAULTS = {target:'https://lnmagic.co.kr/',decoys:['https://www.ikea.com/kr/ko/','https://www.instagram.com/p/CARmsi2HRlV/',...LEGACY_DEFAULTS.decoys.slice(1)],ordinal:5,dot:DOT_PERCENT_DEFAULT,extraTargets:[]};
function forcedHrefs(target,extraTargets){const hrefs=new Set();if(target)hrefs.add(new URL(target).href);for(const item of extraTargets||[])hrefs.add(new URL(item.target).href);return hrefs;}
function withoutForced(values,hrefs){const unique=new Map();for(const value of values){const href=new URL(value).href;if(!hrefs.has(href)&&!unique.has(href))unique.set(href,value);}return [...unique.values()];}
function legacyDefaultsMatch(config){if(config.target!==LEGACY_DEFAULTS.target)return false;const expected=withoutForced(LEGACY_DEFAULTS.decoys,forcedHrefs(config.target,config.extraTargets||[]));return JSON.stringify(config.decoys)===JSON.stringify(expected);}
export function migrateDefaults(config,revision) {if((revision===undefined||revision<DEFAULTS_REVISION)&&legacyDefaultsMatch(config)){const extras=(config.extraTargets||[]).map(item=>({ordinal:item.ordinal,target:item.target}));return {target:DEFAULTS.target,decoys:withoutForced(DEFAULTS.decoys,forcedHrefs(DEFAULTS.target,extras)),ordinal:config.ordinal,dot:config.dot===undefined?DEFAULTS.dot:config.dot,extraTargets:extras};}return config;}
export function url(value) { const u=new URL(String(value).trim()); if(!['https:','http:'].includes(u.protocol)||!u.hostname||u.username||u.password)throw Error('HTTP 또는 HTTPS 주소를 입력하세요.'); return String(value).trim(); }
function extraAssignments(input,primaryOrdinal){if(input.extraTargets===undefined)return [];if(!Array.isArray(input.extraTargets))throw Error('추가 순서 형식이 올바르지 않습니다.');if(input.extraTargets.length>99)throw Error('지정 순서는 목표를 포함해 100개 이하여야 합니다.');const seen=new Set([primaryOrdinal]),extraTargets=[];for(const item of input.extraTargets){if(!item||typeof item!=='object'||Array.isArray(item))throw Error('추가 순서 형식이 올바르지 않습니다.');const ordinalBlank=item.ordinal===undefined||item.ordinal===null||String(item.ordinal).trim()==='';const targetBlank=item.target===undefined||item.target===null||String(item.target).trim()==='';if(ordinalBlank||targetBlank)throw Error('추가한 순서와 사이트를 모두 입력하거나 해당 행을 삭제하세요.');const ordinal=Number(item.ordinal);if(!Number.isSafeInteger(ordinal)||ordinal<1||ordinal>1000000)throw Error('순서는 1-1000000 사이 정수여야 합니다.');if(seen.has(ordinal))throw Error('같은 순서를 두 번 지정할 수 없습니다.');seen.add(ordinal);extraTargets.push({ordinal,target:url(item.target)});}return extraTargets;}
export function settings(input) { const target=input.target?url(input.target):''; const ordinal=Number(input.ordinal); if(!Number.isSafeInteger(ordinal)||ordinal<1||ordinal>1000000)throw Error('순서는 1-1000000 사이 정수여야 합니다.'); const dot=input.dot===undefined?DOT_PERCENT_DEFAULT:assertDot(input.dot); const extraTargets=extraAssignments(input,ordinal); const lines=Array.isArray(input.decoys)?input.decoys:String(input.decoys||'').split('\n'); const prepared=lines.map(x=>x.trim()).filter(Boolean).map(url); const decoys=withoutForced(prepared,forcedHrefs(target,extraTargets)); if(decoys.length>100)throw Error('다른 주소는 100개 이하로 입력하세요.'); const checks=[['목표 링크',target],...extraTargets.map(item=>[`${item.ordinal}번 지정 링크`,item.target]),...decoys.map((value,index)=>[`${index+1}번째 다른 링크`,value])]; for(const [label,payload] of checks){if(!payload)continue;try{encode(payload,1,0);}catch{throw Error(`${label}가 H 오류 복구 QR에 담기에는 너무 깁니다. 주소를 줄여 주세요.`);}} return {target,decoys,ordinal,dot,extraTargets}; }
export function functionMask(version) { const n=version*4+17; const out=Array.from({length:n},()=>Array(n).fill(false)); const mark=(x,y)=>{if(x>=0&&y>=0&&x<n&&y<n)out[y][x]=true;}; for(let i=0;i<n;i++){mark(6,i);mark(i,6);} for(const [cx,cy] of [[3,3],[n-4,3],[3,n-4]])for(let dy=-4;dy<=4;dy++)for(let dx=-4;dx<=4;dx++)mark(cx+dx,cy+dy);
 const count=version===1?0:Math.floor(version/7)+2; const step=version===32?26:Math.ceil((version*4+4)/(count*2-2))*2; const pos=version===1?[]:[6]; for(let p=n-7;pos.length<count;p-=step)pos.splice(1,0,p); for(let i=0;i<pos.length;i++)for(let j=0;j<pos.length;j++){if((i===0&&j===0)||(i===0&&j===pos.length-1)||(i===pos.length-1&&j===0))continue; for(let dy=-2;dy<=2;dy++)for(let dx=-2;dx<=2;dx++)mark(pos[i]+dx,pos[j]+dy);}
 for(let i=0;i<=5;i++)mark(8,i);mark(8,7);mark(8,8);mark(7,8);for(let i=9;i<15;i++)mark(14-i,8);for(let i=0;i<8;i++)mark(n-1-i,8);for(let i=8;i<15;i++)mark(8,n-15+i);mark(8,n-8); if(version>=7)for(let i=0;i<18;i++){mark(n-11+i%3,Math.floor(i/3));mark(Math.floor(i/3),n-11+i%3);} return out; }
export function metadata(qr, Q) { const mask=functionMask(qr.version), n=qr.size; const raw=Q.getNumRawDataModules(qr.version)>>>3; const blocks=Q.NUM_ERROR_CORRECTION_BLOCKS[3][qr.version], ecc=Q.ECC_CODEWORDS_PER_BLOCK[3][qr.version]; const shortLen=Math.floor(raw/blocks), shortBlocks=blocks-raw%blocks; const dataLen=shortLen-ecc; const owners=[]; for(let i=0;i<shortLen+1;i++)for(let b=0;b<blocks;b++){if(i===dataLen&&b<shortBlocks)continue; owners.push(b);} if(owners.length!==raw)throw Error('QR block mapping failed');
 const map=Array.from({length:n},()=>Array(n).fill(null)); let bit=0; for(let right=n-1;right>=1;right-=2){if(right===6)right=5;for(let vert=0;vert<n;vert++)for(let j=0;j<2;j++){const x=right-j,y=((right+1)&2)===0?n-1-vert:vert;if(!mask[y][x]){if(bit<raw*8)map[y][x]={word:bit>>>3,block:owners[bit>>>3]};bit++;}}} return {mask,map,blocks,ecc,limit:Math.max(1,Math.floor(ecc/2)-Math.max(2,Math.ceil(ecc*.15))),raw}; }
export function encode(payload,version=1,mask=-1) { const {QrCode,QrSegment}=globalThis.qrcodegen; return QrCode.encodeSegments(QrSegment.makeSegments(payload),QrCode.Ecc.HIGH,version,40,mask,false); }
export function createQR(payload,version=1,mask=-1,dot=DOT_PERCENT_DEFAULT) { const qr=encode(payload,version,mask);const meta=metadata(qr,globalThis.qrcodegen.QrCode);return {payload,version:qr.version,mask:qr.mask,size:qr.size,dot:assertDot(dot),base:qr.modules.map(r=>r.slice()),edits:new Set(),history:[],meta}; }
export function modules(q) { return q.base.map((r,y)=>r.map((b,x)=>q.edits.has(y*q.size+x)?!b:b)); }
export function budget(q,edits=q.edits) { const words=Array.from({length:q.meta.blocks},()=>new Set()); for(const cell of edits){const p=q.meta.map[Math.floor(cell/q.size)][cell%q.size];if(p)words[p.block].add(p.word);} return words.map(w=>w.size); }
// Shape is independent of edit protection: only the three finder patterns stay square. Circle radius follows q.dot and is not clamped back to 0.5.
export function moduleShape(size,x,y) {return (x<7&&y<7)||(x>=size-7&&y<7)||(x<7&&y>=size-7)?'square':'circle';}
export function geometry(q,edits=q.edits) {const radius=assertDot(q.dot)/200;const shapes=[];modules({...q,edits}).forEach((row,y)=>row.forEach((dark,x)=>{if(dark)shapes.push({shape:moduleShape(q.size,x,y),x:x+4,y:y+4,radius});}));return shapes;}
export function raster(q,scale=10,edits=q.edits) { const n=(q.size+8)*scale,data=new Uint8ClampedArray(n*n*4);data.fill(255);for(const cell of geometry(q,edits)){const square=cell.shape==='square',cx=(cell.x+.5)*scale,cy=(cell.y+.5)*scale,r=cell.radius*scale;const left=Math.max(4*scale,Math.floor(square?cell.x*scale:cx-r)),right=Math.min(n-4*scale,Math.ceil(square?(cell.x+1)*scale:cx+r)),top=Math.max(4*scale,Math.floor(square?cell.y*scale:cy-r)),bottom=Math.min(n-4*scale,Math.ceil(square?(cell.y+1)*scale:cy+r));for(let py=top;py<bottom;py++)for(let px=left;px<right;px++){if(!square&&(px+.5-cx)**2+(py+.5-cy)**2>r*r)continue;const p=(py*n+px)*4;data[p]=data[p+1]=data[p+2]=0;}}return {data,width:n,height:n}; }
export function svg(q) {const n=q.size+8;const shapes=geometry(q).map(cell=>cell.shape==='square'?`<rect x="${cell.x}" y="${cell.y}" width="1" height="1"/>`:`<circle cx="${cell.x+.5}" cy="${cell.y+.5}" r="${cell.radius}"/>`).join('');return `<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 ${n} ${n}" width="${n*16}" height="${n*16}"><rect width="100%" height="100%" fill="white"/><defs><clipPath id="symbol"><rect x="4" y="4" width="${q.size}" height="${q.size}"/></clipPath></defs><g fill="black" clip-path="url(#symbol)">${shapes}</g></svg>`;}
export function decode(q,edits=q.edits) {for(const scale of [10,16]){const r=raster(q,scale,edits);if(globalThis.jsQR(r.data,r.width,r.height,{inversionAttempts:'dontInvert'})?.data!==q.payload)return undefined;}return q.payload;}
// Unbiased Fisher-Yates. A new cycle with two or more decoys does not start on the previous cycle's last draw.
function shuffleBag(items,random){const bag=items.slice();for(let i=bag.length-1;i>0;i--){const j=Math.floor(random()*(i+1));const swap=bag[j];bag[j]=bag[i];bag[i]=swap;}return bag;}
function drawDecoy(decoys,bag,last,random){let pending=Array.isArray(bag)?bag.slice():[];if(!pending.length){pending=shuffleBag(decoys,random);if(last!=null&&pending.length>1&&pending[0]===last){const index=1+Math.floor(random()*(pending.length-1));const swap=pending[index];pending[index]=pending[0];pending[0]=swap;}}return {payload:pending[0],bag:pending.slice(1),last:pending[0]};}
function matchedForced(config,count){if(count===config.ordinal)return config.target;const extra=(config.extraTargets||[]).find(item=>item.ordinal===count);return extra?extra.target:null;}
function gridVersion(config,payload){const forced=[config.target,...(config.extraTargets||[]).map(item=>item.target)].filter(Boolean);return Math.max(4,...forced.map(value=>encode(value).version),...config.decoys.map(value=>encode(value).version),encode(payload).version,encode('QR-1000000000-zzzzzzzzzzzz').version);}
// In-symbol modules, including function patterns and remainder bits, may be edited. Those cells sit outside the data codeword map, so the per-block budget does not cover them; only a same-payload decode can accept or reject the candidate.
export function toggle(q,x,y) {if(!Number.isInteger(x)||!Number.isInteger(y)||x<0||y<0||x>=q.size||y>=q.size)return {ok:false,reason:'bounds'};const next=new Set(q.edits),cell=y*q.size+x;if(next.has(cell))next.delete(cell);else next.add(cell);if(budget(q,next).some(n=>n>q.meta.limit))return {ok:false,reason:'budget'};if(decode(q,next)!==q.payload)return {ok:false,reason:'decode'};q.history.push(new Set(q.edits));q.edits=next;return {ok:true};}
export function undo(q){if(q.history.length)q.edits=q.history.pop();}
export function next(state,random=Math.random) {if(state.frozen)return false;if(!state.config.target)throw Error('먼저 주소를 설정하세요.');const dot=assertDot(state.config.dot);const count=state.counter+1;const forced=matchedForced(state.config,count);let payload,drawn=null;if(forced!==null)payload=forced;else if(state.config.decoys.length)drawn=drawDecoy(state.config.decoys,state.bag,state.last,random),payload=drawn.payload;else payload='QR-'+count+'-'+Array.from({length:12},()=>Math.floor(random()*36).toString(36)).join('');const version=gridVersion(state.config,payload);const firstMask=Math.floor(random()*8);let candidate=null;for(let attempt=0;attempt<8;attempt++){const probe=createQR(payload,version,(firstMask+attempt)%8,dot);if(decode(probe)===payload){candidate=probe;break;}}if(!candidate)throw Error('QR 생성 확인에 실패했습니다.');state.current=candidate;state.counter=count;if(drawn){state.bag=drawn.bag;state.last=drawn.last;}return true;}
export function reset(state){state.counter=0;state.frozen=false;state.current=null;state.bag=[];state.last=null;}
function storedBag(bag,decoys){if(bag===undefined)return [];if(!Array.isArray(bag))throw Error('Invalid bag');const allowed=new Set(decoys),seen=new Set();for(const item of bag){if(typeof item!=='string'||seen.has(item)||!allowed.has(item))throw Error('Invalid bag');url(item);seen.add(item);}return bag.slice();}
function storedLast(last,decoys){if(last===undefined||last===null)return null;if(typeof last!=='string'||!decoys.includes(last))throw Error('Invalid bag');url(last);return last;}
export function serialize(state){return JSON.stringify({schema:1,defaultsRevision:DEFAULTS_REVISION,config:state.config,counter:state.counter,frozen:state.frozen,bag:Array.isArray(state.bag)?state.bag.slice():[],last:typeof state.last==='string'?state.last:null,current:state.current?{payload:state.current.payload,version:state.current.version,mask:state.current.mask,dot:state.current.dot,edits:[...state.current.edits]}:null});}
export function restore(raw){const s=JSON.parse(raw);if(s.schema!==1||!Number.isSafeInteger(s.counter)||s.counter<0||s.counter>1000000000||typeof s.frozen!=='boolean')throw Error('Invalid session');const config=migrateDefaults(settings(s.config),s.defaultsRevision);const bag=storedBag(s.bag,config.decoys),last=storedLast(s.last,config.decoys);if(last!==null&&bag.includes(last))throw Error('Invalid bag');const state={config,counter:s.counter,frozen:s.frozen,current:null,bag,last};if(s.current){const p=s.current;if(typeof p.payload!=='string'||p.payload.length>4096||!Number.isInteger(p.version)||p.version<1||p.version>40||!Number.isInteger(p.mask)||p.mask<0||p.mask>7||!Array.isArray(p.edits)||p.edits.length>10000)throw Error('Invalid QR');const dot=p.dot===undefined?config.dot:assertDot(p.dot);const q=createQR(p.payload,p.version,p.mask,dot);if(q.version!==p.version||q.mask!==p.mask||q.dot!==dot)throw Error('Invalid QR');for(const cell of p.edits){if(!Number.isInteger(cell)||cell<0||cell>=q.size*q.size)throw Error('Invalid cell');q.edits.add(cell);}if(budget(q).some(n=>n>q.meta.limit)||decode(q)!==q.payload)throw Error('Invalid edits');state.current=q;}return state;}
export function save(storage,key,state){try{storage.setItem(key,serialize(state));return true;}catch{return false;}}
export function hit(rect,size,x,y){if(!(rect.width>0&&rect.height>0))return null;const col=Math.floor((x-rect.left)/rect.width*(size+8))-4,row=Math.floor((y-rect.top)/rect.height*(size+8))-4;return col>=0&&row>=0&&col<size&&row<size?{x:col,y:row}:null;}
