export const DEFAULTS = {target:'https://www.instagram.com/p/CARmsi2HRlV/',decoys:['https://lnmagic.co.kr/','https://www.youtube.com/','https://thirtymall.com/','https://www.penguinmagic.com/','https://cafe.naver.com/conjuring','https://www.naver.com/','https://music.youtube.com/'],ordinal:5};
export function url(value) { const u=new URL(String(value).trim()); if(!['https:','http:'].includes(u.protocol)||!u.hostname||u.username||u.password)throw Error('HTTP 또는 HTTPS 주소를 입력하세요.'); return String(value).trim(); }
export function settings(input) { const target=input.target?url(input.target):''; const ordinal=Number(input.ordinal); if(!Number.isSafeInteger(ordinal)||ordinal<1||ordinal>1000000)throw Error('순서는 1-1000000 사이 정수여야 합니다.'); const lines=Array.isArray(input.decoys)?input.decoys:String(input.decoys||'').split('\n'); const targetHref=target?new URL(target).href:null; const unique=new Map(); for(const value of lines.map(x=>x.trim()).filter(Boolean).map(url)){const href=new URL(value).href;if(href!==targetHref&&!unique.has(href))unique.set(href,value);} const decoys=[...unique.values()]; if(decoys.length>100)throw Error('다른 주소는 100개 이하로 입력하세요.'); for(const [label,payload] of [['목표 링크',target],...decoys.map((value,index)=>[`${index+1}번째 다른 링크`,value])]){if(!payload)continue;try{encode(payload,1,0);}catch{throw Error(`${label}가 H 오류 복구 QR에 담기에는 너무 깁니다. 주소를 줄여 주세요.`);}} return {target,decoys,ordinal}; }
export function functionMask(version) { const n=version*4+17; const out=Array.from({length:n},()=>Array(n).fill(false)); const mark=(x,y)=>{if(x>=0&&y>=0&&x<n&&y<n)out[y][x]=true;}; for(let i=0;i<n;i++){mark(6,i);mark(i,6);} for(const [cx,cy] of [[3,3],[n-4,3],[3,n-4]])for(let dy=-4;dy<=4;dy++)for(let dx=-4;dx<=4;dx++)mark(cx+dx,cy+dy);
 const count=version===1?0:Math.floor(version/7)+2; const step=version===32?26:Math.ceil((version*4+4)/(count*2-2))*2; const pos=version===1?[]:[6]; for(let p=n-7;pos.length<count;p-=step)pos.splice(1,0,p); for(let i=0;i<pos.length;i++)for(let j=0;j<pos.length;j++){if((i===0&&j===0)||(i===0&&j===pos.length-1)||(i===pos.length-1&&j===0))continue; for(let dy=-2;dy<=2;dy++)for(let dx=-2;dx<=2;dx++)mark(pos[i]+dx,pos[j]+dy);}
 for(let i=0;i<=5;i++)mark(8,i);mark(8,7);mark(8,8);mark(7,8);for(let i=9;i<15;i++)mark(14-i,8);for(let i=0;i<8;i++)mark(n-1-i,8);for(let i=8;i<15;i++)mark(8,n-15+i);mark(8,n-8); if(version>=7)for(let i=0;i<18;i++){mark(n-11+i%3,Math.floor(i/3));mark(Math.floor(i/3),n-11+i%3);} return out; }
export function metadata(qr, Q) { const mask=functionMask(qr.version), n=qr.size; const raw=Q.getNumRawDataModules(qr.version)>>>3; const blocks=Q.NUM_ERROR_CORRECTION_BLOCKS[3][qr.version], ecc=Q.ECC_CODEWORDS_PER_BLOCK[3][qr.version]; const shortLen=Math.floor(raw/blocks), shortBlocks=blocks-raw%blocks; const dataLen=shortLen-ecc; const owners=[]; for(let i=0;i<shortLen+1;i++)for(let b=0;b<blocks;b++){if(i===dataLen&&b<shortBlocks)continue; owners.push(b);} if(owners.length!==raw)throw Error('QR block mapping failed');
 const map=Array.from({length:n},()=>Array(n).fill(null)); let bit=0; for(let right=n-1;right>=1;right-=2){if(right===6)right=5;for(let vert=0;vert<n;vert++)for(let j=0;j<2;j++){const x=right-j,y=((right+1)&2)===0?n-1-vert:vert;if(!mask[y][x]){if(bit<raw*8)map[y][x]={word:bit>>>3,block:owners[bit>>>3]};bit++;}}} return {mask,map,blocks,ecc,limit:Math.max(1,Math.floor(ecc/2)-Math.max(2,Math.ceil(ecc*.15))),raw}; }
export function encode(payload,version=1,mask=-1) { const {QrCode,QrSegment}=globalThis.qrcodegen; return QrCode.encodeSegments(QrSegment.makeSegments(payload),QrCode.Ecc.HIGH,version,40,mask,false); }
export function createQR(payload,version=1,mask=-1) { const qr=encode(payload,version,mask);const meta=metadata(qr,globalThis.qrcodegen.QrCode);return {payload,version:qr.version,mask:qr.mask,size:qr.size,base:qr.modules.map(r=>r.slice()),edits:new Set(),history:[],meta}; }
export function modules(q) { return q.base.map((r,y)=>r.map((b,x)=>q.edits.has(y*q.size+x)?!b:b)); }
export function budget(q,edits=q.edits) { const words=Array.from({length:q.meta.blocks},()=>new Set()); for(const cell of edits){const p=q.meta.map[Math.floor(cell/q.size)][cell%q.size];if(p)words[p.block].add(p.word);} return words.map(w=>w.size); }
export function raster(q,scale=10,edits=q.edits) { const n=(q.size+8)*scale,data=new Uint8ClampedArray(n*n*4);data.fill(255);const matrix=modules({...q,edits});for(let y=0;y<q.size;y++)for(let x=0;x<q.size;x++)if(matrix[y][x])for(let dy=0;dy<scale;dy++)for(let dx=0;dx<scale;dx++){if(!q.meta.mask[y][x]&&((dx+.5-scale/2)**2+(dy+.5-scale/2)**2)>(scale*.46)**2)continue;const p=(((y+4)*scale+dy)*n+(x+4)*scale+dx)*4;data[p]=data[p+1]=data[p+2]=0;}return {data,width:n,height:n}; }
export function decode(q,edits=q.edits) {const r=raster(q,10,edits);return globalThis.jsQR(r.data,r.width,r.height,{inversionAttempts:'dontInvert'})?.data;}
export function toggle(q,x,y) {if(!Number.isInteger(x)||!Number.isInteger(y)||x<0||y<0||x>=q.size||y>=q.size||q.meta.mask[y][x]||!q.meta.map[y][x])return {ok:false,reason:'protected'};const next=new Set(q.edits),cell=y*q.size+x;if(next.has(cell))next.delete(cell);else next.add(cell);if(budget(q,next).some(n=>n>q.meta.limit))return {ok:false,reason:'budget'};if(decode(q,next)!==q.payload)return {ok:false,reason:'decode'};q.history.push(new Set(q.edits));q.edits=next;return {ok:true};}
export function undo(q){if(q.history.length)q.edits=q.history.pop();}
export function next(state,random=Math.random) {if(state.frozen)return false;if(!state.config.target)throw Error('먼저 주소를 설정하세요.');const count=state.counter+1;let payload;if(count===state.config.ordinal)payload=state.config.target;else if(state.config.decoys.length){payload=state.config.decoys[Math.floor(random()*state.config.decoys.length)];}else payload='QR-'+count+'-'+Array.from({length:12},()=>Math.floor(random()*36).toString(36)).join('');const version=Math.max(encode(state.config.target).version,...state.config.decoys.map(p=>encode(p).version),encode(payload).version,encode('QR-1000000000-zzzzzzzzzzzz').version);const candidate=createQR(payload,version,Math.floor(random()*8));if(decode(candidate)!==payload)throw Error('QR 생성 확인에 실패했습니다.');state.current=candidate;state.counter=count;return true;}
export function reset(state){state.counter=0;state.frozen=false;state.current=null;}
export function serialize(state){return JSON.stringify({schema:1,config:state.config,counter:state.counter,frozen:state.frozen,current:state.current?{payload:state.current.payload,version:state.current.version,mask:state.current.mask,edits:[...state.current.edits]}:null});}
export function restore(raw){const s=JSON.parse(raw);if(s.schema!==1||!Number.isSafeInteger(s.counter)||s.counter<0||s.counter>1000000000||typeof s.frozen!=='boolean')throw Error('Invalid session');const config=settings(s.config);const state={config,counter:s.counter,frozen:s.frozen,current:null};if(s.current){const p=s.current;if(typeof p.payload!=='string'||p.payload.length>4096||!Number.isInteger(p.version)||p.version<1||p.version>40||!Number.isInteger(p.mask)||p.mask<0||p.mask>7||!Array.isArray(p.edits)||p.edits.length>10000)throw Error('Invalid QR');const q=createQR(p.payload,p.version,p.mask);if(q.version!==p.version)throw Error('Invalid version');for(const cell of p.edits){if(!Number.isInteger(cell)||cell<0||cell>=q.size*q.size||q.meta.mask[Math.floor(cell/q.size)][cell%q.size]||!q.meta.map[Math.floor(cell/q.size)][cell%q.size])throw Error('Invalid cell');q.edits.add(cell);}if(budget(q).some(n=>n>q.meta.limit)||decode(q)!==q.payload)throw Error('Invalid edits');state.current=q;}return state;}
export function save(storage,key,state){try{storage.setItem(key,serialize(state));return true;}catch{return false;}}
export function hit(rect,size,x,y){if(!(rect.width>0&&rect.height>0))return null;const col=Math.floor((x-rect.left)/rect.width*(size+8))-4,row=Math.floor((y-rect.top)/rect.height*(size+8))-4;return col>=0&&row>=0&&col<size&&row<size?{x:col,y:row}:null;}
