create table if not exists public.quest_badges (
  code text primary key,
  track text not null,
  level integer,
  name text not null,
  material text not null,
  symbol text not null,
  rarity text not null,
  threshold integer,
  is_secret boolean not null default false,
  manual_only boolean not null default false,
  public_description text not null,
  secret_hint text,
  sort_order integer not null default 0,
  created_at timestamptz not null default now()
);

create table if not exists public.user_quest_badges (
  user_id uuid not null,
  badge_code text not null references public.quest_badges(code) on delete cascade,
  awarded_at timestamptz not null default now(),
  awarded_reason text,
  awarded_by uuid,
  primary key (user_id, badge_code)
);

create table if not exists public.answer_helpful_votes (
  answer_id uuid not null,
  user_id uuid not null,
  created_at timestamptz not null default now(),
  primary key (answer_id, user_id)
);

insert into public.quest_badges (
  code,
  track,
  level,
  name,
  material,
  symbol,
  rarity,
  threshold,
  is_secret,
  manual_only,
  public_description,
  secret_hint,
  sort_order
) values
  ('total_records_1', 'total_records', 1, '첫 흔적', '흑철', '작은 서판', 'common', 1, false, false, '전체 기록 1회 달성', null, 101),
  ('total_records_2', 'total_records', 2, '기록 견습생', '청강', '카탈로그 카드', 'uncommon', 10, false, false, '전체 기록 10회 달성', null, 102),
  ('total_records_3', 'total_records', 3, '기록 수집가', '운철', '두루마리', 'rare', 30, false, false, '전체 기록 30회 달성', null, 103),
  ('total_records_4', 'total_records', 4, '보관소 관리인', '아다만틴', '서류함', 'epic', 60, false, false, '전체 기록 60회 달성', null, 104),
  ('total_records_5', 'total_records', 5, '칼리단 연대기 작가', '별철', '장정본', 'legendary', 100, false, false, '전체 기록 100회 달성', null, 105),
  ('questions_1', 'questions', 1, '첫 물음', '흑철', '물음 서판', 'common', 1, false, false, '질문 1회 달성', null, 201),
  ('questions_2', 'questions', 2, '탐구자', '청강', '나침반', 'uncommon', 5, false, false, '질문 5회 달성', null, 202),
  ('questions_3', 'questions', 3, '길 찾는 사람', '운철', '지도 조각', 'rare', 10, false, false, '질문 10회 달성', null, 203),
  ('questions_4', 'questions', 4, '깊은 탐구자', '아다만틴', '별자리 지도', 'epic', 20, false, false, '질문 20회 달성', null, 204),
  ('questions_5', 'questions', 5, '문을 여는 질문자', '별철', '열린 아치', 'legendary', 40, false, false, '질문 40회 달성', null, 205),
  ('answers_1', 'answers', 1, '첫 안내', '흑철', '작은 나침반', 'common', 1, false, false, '답변 1회 달성', null, 301),
  ('answers_2', 'answers', 2, '길잡이', '청강', '지도 조각', 'uncommon', 5, false, false, '답변 5회 달성', null, 302),
  ('answers_3', 'answers', 3, '살롱 안내자', '운철', '별자리', 'rare', 10, false, false, '답변 10회 달성', null, 303),
  ('answers_4', 'answers', 4, '문제 해결사', '아다만틴', '망원경', 'epic', 30, false, false, '답변 30회 달성', null, 304),
  ('answers_5', 'answers', 5, '칼리단 항해사', '별철', '천구의', 'legendary', 50, false, false, '답변 50회 달성', null, 305),
  ('answer_helpful_votes_1', 'answer_helpful_votes', 1, '첫 감사', '흑철', '작은 손짓', 'common', 1, false, false, '도움됐어요 1회 달성', null, 401),
  ('answer_helpful_votes_2', 'answer_helpful_votes', 2, '작은 길잡이', '청강', '손전등', 'uncommon', 5, false, false, '도움됐어요 5회 달성', null, 402),
  ('answer_helpful_votes_3', 'answer_helpful_votes', 3, '고마운 답변자', '운철', '별표 지도', 'rare', 15, false, false, '도움됐어요 15회 달성', null, 403),
  ('answer_helpful_votes_4', 'answer_helpful_votes', 4, '신뢰의 답변', '아다만틴', '인장', 'epic', 30, false, false, '도움됐어요 30회 달성', null, 404),
  ('answer_helpful_votes_5', 'answer_helpful_votes', 5, '칼리단 조언자', '별철', '빛나는 나침반', 'legendary', 60, false, false, '도움됐어요 60회 달성', null, 405),
  ('free_posts_1', 'free_posts', 1, '첫 낙서', '흑철', '잉크방울', 'common', 1, false, false, '자유 기록 1회 달성', null, 501),
  ('free_posts_2', 'free_posts', 2, '살롱 단골', '청강', '작은 노트', 'uncommon', 10, false, false, '자유 기록 10회 달성', null, 502),
  ('free_posts_3', 'free_posts', 3, '밤의 이야기꾼', '운철', '잉크병', 'rare', 30, false, false, '자유 기록 30회 달성', null, 503),
  ('free_posts_4', 'free_posts', 4, '자유 기록가', '아다만틴', '말풍선 문장', 'epic', 50, false, false, '자유 기록 50회 달성', null, 504),
  ('free_posts_5', 'free_posts', 5, '살롱의 목소리', '별철', '원형 살롱 문장', 'legendary', 70, false, false, '자유 기록 70회 달성', null, 505),
  ('event_reviews_1', 'event_reviews', 1, '첫 참석 기록', '흑철', '빈 의자', 'common', 1, false, false, '모임 기록 1회 달성', null, 601),
  ('event_reviews_2', 'event_reviews', 2, '다시 온 사람', '청강', '찻잔', 'uncommon', 2, false, false, '모임 기록 2회 달성', null, 602),
  ('event_reviews_3', 'event_reviews', 3, '모임 기록자', '운철', '원탁', 'rare', 3, false, false, '모임 기록 3회 달성', null, 603),
  ('event_reviews_4', 'event_reviews', 4, '살롱의 증인', '아다만틴', '사진 프레임', 'epic', 5, false, false, '모임 기록 5회 달성', null, 604),
  ('event_reviews_5', 'event_reviews', 5, '플랜비 연대기', '별철', '살롱 문장', 'legendary', 10, false, false, '모임 기록 10회 달성', null, 605),
  ('tool_reviews_1', 'tool_reviews', 1, '첫 도구 기록', '흑철', '카드 케이스', 'common', 1, false, false, '도구 기록 1회 달성', null, 701),
  ('tool_reviews_2', 'tool_reviews', 2, '도구 견습생', '청강', '브라스 라벨', 'uncommon', 2, false, false, '도구 기록 2회 달성', null, 702),
  ('tool_reviews_3', 'tool_reviews', 3, '장비 감별사', '운철', '렌즈', 'rare', 5, false, false, '도구 기록 5회 달성', null, 703),
  ('tool_reviews_4', 'tool_reviews', 4, '보관함 큐레이터', '아다만틴', '도구함', 'epic', 10, false, false, '도구 기록 10회 달성', null, 704),
  ('tool_reviews_5', 'tool_reviews', 5, '마도구 감정사', '별철', '진열장', 'legendary', 20, false, false, '도구 기록 20회 달성', null, 705),
  ('secret_unanswered_compass', 'secret', null, '등 뒤의 나침반', '월광석', '나침반 뒤의 그림자', 'secret', null, true, false, '비밀 조건을 달성하면 모습을 드러내는 퀘스트 배지입니다.', '아무도 가리키지 않던 길을 처음 가리킨 사람', 801),
  ('secret_night_scribe', 'secret', null, '밤의 서기관', '흑요석', '달과 잉크', 'secret', null, true, false, '비밀 조건을 달성하면 모습을 드러내는 퀘스트 배지입니다.', '모두가 잠든 시간에도 기록소의 불은 꺼지지 않음', 802),
  ('secret_old_shelf', 'secret', null, '오래된 서가', '월광석', '먼지 쌓인 서가', 'secret', null, true, false, '비밀 조건을 달성하면 모습을 드러내는 퀘스트 배지입니다.', '먼지가 쌓인 기록을 다시 열어본 사람', 803),
  ('secret_quiet_applause', 'secret', null, '조용한 박수', '에테르 봉인', '작은 박수 문장', 'secret', null, true, false, '비밀 조건을 달성하면 모습을 드러내는 퀘스트 배지입니다.', '큰 박수보다 오래 남는 한마디가 있음', 804),
  ('secret_kali_notice', 'secret', null, '칼리의 눈길', '붉은 별철', '붉은 별', 'secret', null, true, true, '비밀 조건을 달성하면 모습을 드러내는 퀘스트 배지입니다.', '주인장이 조용히 기억해둔 기록', 805)
on conflict (code) do update set
  track = excluded.track,
  level = excluded.level,
  name = excluded.name,
  material = excluded.material,
  symbol = excluded.symbol,
  rarity = excluded.rarity,
  threshold = excluded.threshold,
  is_secret = excluded.is_secret,
  manual_only = excluded.manual_only,
  public_description = excluded.public_description,
  secret_hint = excluded.secret_hint,
  sort_order = excluded.sort_order;
